services:
  evolution-api:
    image: evoapicloud/evolution-api:v2.3.1
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SERVER_TYPE: ${SERVER_TYPE}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_URL: ${SERVER_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_BAILEYS: ${LOG_BAILEYS}
      DEL_INSTANCE: ${DEL_INSTANCE}
      DATABASE_PROVIDER: ${DATABASE_PROVIDER}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DATABASE_CONNECTION_URI: ${DATABASE_CONNECTION_URI}
      DATABASE_CONNECTION_CLIENT_NAME: ${DATABASE_CONNECTION_CLIENT_NAME}
      DATABASE_SAVE_DATA_INSTANCE: ${DATABASE_SAVE_DATA_INSTANCE}
      DATABASE_SAVE_DATA_NEW_MESSAGE: ${DATABASE_SAVE_DATA_NEW_MESSAGE}
      DATABASE_SAVE_MESSAGE_UPDATE: ${DATABASE_SAVE_MESSAGE_UPDATE}
      DATABASE_SAVE_DATA_CONTACTS: ${DATABASE_SAVE_DATA_CONTACTS}
      DATABASE_SAVE_DATA_CHATS: ${DATABASE_SAVE_DATA_CHATS}
      WEBHOOK_GLOBAL_ENABLED: ${WEBHOOK_GLOBAL_ENABLED}
      WEBHOOK_GLOBAL_URL: ${WEBHOOK_GLOBAL_URL}
      WEBHOOK_EVENTS_MESSAGES_UPSERT: ${WEBHOOK_EVENTS_MESSAGES_UPSERT}
      WA_BUSINESS_TOKEN_WEBHOOK: ${WA_BUSINESS_TOKEN_WEBHOOK}
      WA_BUSINESS_URL: ${WA_BUSINESS_URL}
      WA_BUSINESS_VERSION: ${WA_BUSINESS_VERSION}
      WA_BUSINESS_LANGUAGE: ${WA_BUSINESS_LANGUAGE}
      CONFIG_SESSION_PHONE_NAME: ${CONFIG_SESSION_PHONE_NAME}
      N8N_ENABLED: ${N8N_ENABLED}
      CACHE_REDIS_ENABLED: ${CACHE_REDIS_ENABLED}
      CACHE_REDIS_URI: ${CACHE_REDIS_URI}
      CACHE_REDIS_PREFIX_KEY: ${CACHE_REDIS_PREFIX_KEY}
      AUTHENTICATION_TYPE_API_KEY_ENABLED: ${AUTHENTICATION_TYPE_API_KEY_ENABLED}
      AUTHENTICATION_API_KEY: ${AUTHENTICATION_API_KEY}
      AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: ${AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES}
      LANGUAGE: ${LANGUAGE}
    volumes:
      - ./evolution-docker-data:/evolution/instances
      - /etc/localtime:/etc/localtime:ro
    networks:
      - loomie-network
    depends_on:
      - postgres
      - redis

  n8n:
    image: n8nio/n8n:1.106.3
    restart: always
    ports:
      - "5678:5678"
    environment:
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      N8N_HOST: ${N8N_HOST}
      WEBHOOK_URL: ${WEBHOOK_URL}
      VUE_APP_N8N_PROTOCOL: ${VUE_APP_N8N_PROTOCOL}
      VUE_APP_N8N_HOST: ${VUE_APP_N8N_HOST}
      GENERIC_TIMEOUT: ${GENERIC_TIMEOUT}
      N8N_SECURE_COOKIE: ${N8N_SECURE_COOKIE}
      N8N_COOKIE_DOMAIN: ${N8N_COOKIE_DOMAIN}
      N8N_BASIC_AUTH_ACTIVE: ${N8N_BASIC_AUTH_ACTIVE}
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      NODE_FUNCTION_ALLOW_EXTERNAL: ${NODE_FUNCTION_ALLOW_EXTERNAL}
    volumes:
      - n8n-docker-data:/home/node/.n8n
    networks:
      - loomie-network
    depends_on:
      - evolution-api

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - loomie-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - ./redis-data:/data
    networks:
      - loomie-network

networks:
  loomie-network:
    external: true

volumes:
  n8n-docker-data:
  postgres-data:
  redis-data:
  evolution-docker-data: